### ISSUE TITLE
Code blocks should returned as <p>

### ISSUE THREAD

**Issue by aliuk2012** [alphagov/govuk-forms-markdown#8]
```
# using `code`
```

or 

```
# using ```code``` 
```

Should return unstyle with `<p>` wrapped around.

**Comment by DavidBiddle** [comment]
Should be resolved in #15.

Single backticks \`\` are inline quotes, so they shouldn't render in paragraph tags - we should just return the content as normal text.

I think having `disable_indented_code_blocks: true` and `fenced_code_blocks: false` settings prevents block code rendering.
